apiVersion: v1
kind: Service
metadata:  
  name: test-nodeport
spec:
  selector:    
    app: argocd-server
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP

    //kubectl port-forward -n argocd service/argocd-server 80:30036