name: bramble-config
on:
  push:
    branches: [ "main" ]
    paths:
      - cluster/**

  workflow_dispatch:

jobs:
  configure-bramble:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: infrastructure
        
    steps:
    - uses: actions/checkout@v2
    - name: Run Ansible Playbook
      run: ansible-playbook site.yml -i inventory/bramble-cluster/hosts.ini
