name: application-config
on:
  push:
    branches: [ "main" ]
    paths:
      - infrastructure/**

  workflow_dispatch:

jobs:
  configure-applications:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: infrastructure

    steps:
    - uses: actions/checkout@v2
    - name: Run Terraform Init
      run: terraform init
    - name: Run Terraform Plan
      run: terraform plan