name: bramble-config
on:
  push:
    branches: [ "main" ]
    paths:
      - infrastructure/**

  workflow_dispatch:

jobs:
  configure-bramble:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Run Terraform Init
      run: terraform init