apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-routes
  namespace: argocd
spec:
  project: root-cluster
  source:
    path: apps/ingress-routes
    repoURL: 'https://github.com/petemessina/bramble-config'
    targetRevision: main
  destination: 
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true