apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-cluster
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argo
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/clusterdefault
    repoURL: 'https://github.com/petemessina/bramble-config'
    targetRevision: main
  project: root-cluster